"""
Training Script for the Double-Well Action CNN

Trains a 1D CNN to learn the Euclidean action S[q] for the double-well
potential from instanton-cloud data generated by data_generator.py.

Usage
-----
Edit the CONFIGURATION block below, then run:
    python train.py

Output
------
Results are written to results/dw_cnn_N<N_tau>_<timestamp>/:
    dw_action_cnn_N<N_tau>.pth   trained model checkpoint
    training_history.png
    evaluation_results.png
    gradient_check.png
    hessian_check.png            (only when RUN_HESSIAN_CHECK = True)
    checkpoint_latest.pth        (only when CHECKPOINT_EVERY > 0)
"""

import json
from datetime import datetime
from pathlib import Path

import numpy as np
import torch

from cnn_architecture import create_1d_cnn
from cnn_functions import (
    evaluate_model,
    plot_evaluation_results,
    plot_gradient_check,
    plot_hessian_check,
    plot_training_history,
    train_model,
)
from DoubleWell import DoubleWellPath


# ============================================================================
# CONFIGURATION  — edit this block before running
# ============================================================================

# Path to a dataset directory produced by data_generator.py.
DATA_DIR = Path("/your/path/here")

# Output root; runs are written to OUT_DIR/dw_cnn_N<N_tau>_<timestamp>/
OUT_DIR  = Path("results")

# --- Training ---
N_EPOCHS        = 20
BATCH_SIZE      = 64
LEARNING_RATE   = 1e-3
TRAIN_FRACTION  = 0.8
RANDOM_SEED     = 42

# --- Loss terms ---
LAMBDA_GRAD       = 10.0   # gradient matching weight        (0 = off)
USE_Z2_AUG        = False   # Z2 flip augmentation during gradient matching
LAMBDA_SADDLE     = 0.0    # saddle-point pinning weight      (0 = off)
N_SADDLE          = 5      # number of instanton profiles for saddle pinning

# --- Architecture ---
N_CHANNELS      = 32
KERNEL_SIZES    = [3, 3, 3]

# --- Checkpointing & diagnostics ---
CHECKPOINT_EVERY   = 50    # save checkpoint every N epochs (0 = off)
RUN_HESSIAN_CHECK  = True  # compute and plot Hessian spectrum at the instanton


# ============================================================================
# DATA
# ============================================================================

def load_raw_dataset(data_dir: Path) -> dict:
    """
    Load configs, actions, gradients and params.json from a data directory.

    Returns a dict with keys: configs, actions, gradients, params.
    """
    if not data_dir.exists():
        raise FileNotFoundError(
            f"Dataset directory not found: {data_dir}\n"
            "Set DATA_DIR at the top of train.py and generate data with data_generator.py."
        )

    required = ["configs.npy", "actions.npy", "gradients.npy", "params.json"]
    missing  = [f for f in required if not (data_dir / f).exists()]
    if missing:
        raise FileNotFoundError(f"Missing files in {data_dir}: {missing}")

    with open(data_dir / "params.json") as f:
        params = json.load(f)

    return {
        "configs"   : np.load(data_dir / "configs.npy"),
        "actions"   : np.load(data_dir / "actions.npy"),
        "gradients" : np.load(data_dir / "gradients.npy"),
        "params"    : params,
    }


def prepare_data(raw: dict, train_frac: float, path: DoubleWellPath) -> dict:
    """
    Normalise, split, and convert to PyTorch tensors.

    Normalisation
    -------------
    Actions are shifted by S_inst (continuum) and scaled by the dataset std,
    so the network sees targets centred on the instanton action.
    Gradients are scaled by the same std (no shift).
    Configurations are left untouched (already in physical units).

    Returns a dict with keys:
        train_q, train_S, train_grad_S,
        val_q, val_S, val_grad_S,
        val_configs, val_grads_np,   <- numpy arrays kept for plotting
        S_anchor, std_S, N_tau.
    """
    configs, actions, gradients = raw["configs"], raw["actions"], raw["gradients"]
    N_total, N_tau = configs.shape

    S_anchor       = path.S_inst_continuum
    std_S          = actions.std()
    actions_norm   = (actions   - S_anchor) / std_S
    gradients_norm = gradients  / std_S

    idx     = np.random.permutation(N_total)
    n_train = int(train_frac * N_total)
    t_idx, v_idx = idx[:n_train], idx[n_train:]

    def to_q(cfg): return torch.FloatTensor(cfg).unsqueeze(1)   # (N, 1, N_tau)
    def to_s(arr): return torch.FloatTensor(arr).flatten()

    return {
        "train_q"      : to_q(configs[t_idx]),
        "train_S"      : to_s(actions_norm[t_idx]),
        "train_grad_S" : torch.FloatTensor(gradients_norm[t_idx]),
        "val_q"        : to_q(configs[v_idx]),
        "val_S"        : to_s(actions_norm[v_idx]),
        "val_grad_S"   : torch.FloatTensor(gradients_norm[v_idx]),
        "val_configs"  : configs[v_idx],           # raw numpy, for plotting
        "val_grads_np" : gradients[v_idx],          # physical units, for plotting
        "S_anchor"     : float(S_anchor),
        "std_S"        : float(std_S),
        "N_tau"        : N_tau,
    }


# ============================================================================
# HELPERS
# ============================================================================

def build_path(params: dict) -> DoubleWellPath:
    """Reconstruct DoubleWellPath from dataset metadata."""
    return DoubleWellPath(
        N_tau   = params["N_tau"],
        beta    = params["beta"],
        lam     = params["lam"],
        a       = params["a"],
        m       = params.get("m",       1.0),
        bc      = params.get("bc",      "dirichlet"),
        mu_bias = params.get("mu_bias", 0.0),
        tau_pin = params.get("tau_pin", None),
    )


def make_saddle_configs(
    path: DoubleWellPath,
    n: int,
    tau0_min: float,
    tau0_max: float,
) -> list[torch.Tensor]:
    """
    Build classical kink profiles for saddle-point pinning.

    The saddle-pinning loss penalises ||dS_theta/dq||^2 at these profiles,
    teaching the network that classical solutions are stationary points
    of the action. The centres tau0 should span the same range as the
    training data, which is why the bounds are read from params.json
    (tau0_frac_min/max * beta) rather than hardcoded.

    Delegates to DoubleWellPath.classical_kink so that boundary conditions
    and discretisation are handled consistently with the rest of the codebase.
    """
    tau0_list = np.linspace(tau0_min, tau0_max, n)
    return [
        torch.FloatTensor(path.classical_kink(tau0)).unsqueeze(0).unsqueeze(0)
        for tau0 in tau0_list
    ]


def compute_val_gradients(model: torch.nn.Module, val_q: torch.Tensor) -> np.ndarray:
    """Return CNN-predicted gradients on the full validation set."""
    model.eval()
    q_leaf = val_q.detach().clone().requires_grad_(True)
    S_pred = model(q_leaf).squeeze()
    grad_pred, = torch.autograd.grad(S_pred.sum(), q_leaf)
    return grad_pred.squeeze(1).detach().cpu().numpy()


def compute_hessian_check(
    model: torch.nn.Module,
    path: DoubleWellPath,
    std_S: float,
) -> tuple[np.ndarray, np.ndarray]:
    """
    Compare exact and CNN Hessian spectra at the classical instanton.

    The CNN Hessian is computed by central finite differences on the autograd
    gradient, then rescaled to physical units via std_S.
    """
    q_cl       = path.classical_kink()
    eigs_exact = np.linalg.eigvalsh(path.get_hessian(q_cl))

    q_cl_t = torch.FloatTensor(q_cl).unsqueeze(0).unsqueeze(0)
    eps_fd = 1e-3
    H_cnn  = np.zeros((path.N_tau, path.N_tau))

    for i in range(path.N_tau):
        q_p = q_cl_t.clone().requires_grad_(True)
        q_m = q_cl_t.clone().requires_grad_(True)
        q_p.data[0, 0, i] += eps_fd
        q_m.data[0, 0, i] -= eps_fd

        g_p, = torch.autograd.grad(model(q_p).squeeze(), q_p)
        g_m, = torch.autograd.grad(model(q_m).squeeze(), q_m)
        H_cnn[:, i] = (g_p.squeeze() - g_m.squeeze()).detach().numpy() / (2 * eps_fd)

    H_cnn    = 0.5 * (H_cnn + H_cnn.T)
    eigs_cnn = np.linalg.eigvalsh(std_S * H_cnn)

    return eigs_exact, eigs_cnn


def save_model(
    model: torch.nn.Module,
    model_path: Path,
    *,
    data: dict,
    train_losses: list[float],
    val_losses: list[float],
    eval_results: dict,
    timestamp: str,
    physics: dict,
) -> None:
    torch.save(
        {
            "model_state_dict": model.state_dict(),
            "norm_stats": {
                "S_anchor": data["S_anchor"],
                "std_S":    data["std_S"],
            },
            "architecture": {
                "n_channels":   N_CHANNELS,
                "kernel_sizes": KERNEL_SIZES,
            },
            "N_tau":        data["N_tau"],
            "physics":      physics,
            "train_losses": train_losses,
            "val_losses":   val_losses,
            "eval_results": eval_results,
            "timestamp":    timestamp,
        },
        model_path,
    )


# ============================================================================
# MAIN
# ============================================================================

def main() -> None:
    np.random.seed(RANDOM_SEED)
    torch.manual_seed(RANDOM_SEED)

    print("=" * 60)
    print("DOUBLE-WELL: TRAINING ACTION CNN")
    print("=" * 60)
    print(f"Data directory: {DATA_DIR}\n")

    # ----------------------------------------------------------------
    # 1. Load, prepare data, and build saddle configs
    # ----------------------------------------------------------------
    print("=" * 60)
    print("1. DATA")
    print("=" * 60)

    raw  = load_raw_dataset(DATA_DIR)
    path = build_path(raw["params"])
    data = prepare_data(raw, TRAIN_FRACTION, path)

    print(f"  Configurations : {raw['configs'].shape[0]} x N_tau={data['N_tau']}")
    print(f"  Action         : mean={raw['actions'].mean():.4f}, std={data['std_S']:.4f}")
    print(f"  S_anchor       : {data['S_anchor']:.4f}  (continuum S_inst)")
    print(f"  Train / val    : {data['train_q'].shape[0]} / {data['val_q'].shape[0]}")

    saddle_configs = None
    if LAMBDA_SADDLE > 0.0:
        params   = raw["params"]
        tau0_min = params["tau0_frac_min"] * params["beta"]
        tau0_max = params["tau0_frac_max"] * params["beta"]
        saddle_configs = make_saddle_configs(path, N_SADDLE, tau0_min, tau0_max)
        print(f"  Saddle pinning : {N_SADDLE} classical kink profiles "
              f"(tau0 in [{tau0_min:.2f}, {tau0_max:.2f}])")

    # ----------------------------------------------------------------
    # 2. Model
    # ----------------------------------------------------------------
    print("\n" + "=" * 60)
    print("2. MODEL")
    print("=" * 60)

    model    = create_1d_cnn(n_channels=N_CHANNELS, kernel_sizes=KERNEL_SIZES)
    n_params = sum(p.numel() for p in model.parameters())
    print(f"  Channels : {N_CHANNELS}  |  Kernels : {KERNEL_SIZES}  |  Params : {n_params:,}")
    print(model)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    run_dir   = OUT_DIR / f"dw_cnn_N{data['N_tau']}_{timestamp}"
    run_dir.mkdir(parents=True, exist_ok=True)

    ckpt_path = str(run_dir / "checkpoint_latest.pth") if CHECKPOINT_EVERY > 0 else None

    # ----------------------------------------------------------------
    # 3. Train
    # ----------------------------------------------------------------
    print("\n" + "=" * 60)
    print("3. TRAINING")
    print("=" * 60)

    train_losses, val_losses = train_model(
        model,
        data["train_q"],    data["train_S"],
        data["val_q"],      data["val_S"],
        n_epochs            = N_EPOCHS,
        batch_size          = BATCH_SIZE,
        learning_rate       = LEARNING_RATE,
        lambda_grad         = LAMBDA_GRAD,
        train_grad_S        = data["train_grad_S"],
        val_grad_S          = data["val_grad_S"],
        use_z2_augmentation = USE_Z2_AUG,
        lambda_saddle       = LAMBDA_SADDLE,
        saddle_configs      = saddle_configs,
        checkpoint_path     = ckpt_path,
        checkpoint_every    = CHECKPOINT_EVERY,
        verbose             = True,
    )

    # ----------------------------------------------------------------
    # 4. Evaluation and diagnostics
    # ----------------------------------------------------------------
    print("\n" + "=" * 60)
    print("4. EVALUATION")
    print("=" * 60)

    eval_results   = evaluate_model(model, data["val_q"], data["val_S"], verbose=True)
    val_grads_pred = compute_val_gradients(model, data["val_q"])

    val_grads_norm = data["val_grads_np"] / data["std_S"]
    grad_mse = np.mean((val_grads_pred - val_grads_norm) ** 2)
    grad_mae = np.mean(np.abs(val_grads_pred - val_grads_norm))
    print(f"  Gradient MSE (normalised): {grad_mse:.6f}")
    print(f"  Gradient MAE (normalised): {grad_mae:.6f}")

    eigs_exact = eigs_cnn = None
    if RUN_HESSIAN_CHECK:
        print("\n  Hessian spectrum at classical instanton:")
        eigs_exact, eigs_cnn = compute_hessian_check(model, path, data["std_S"])
        print(f"    Exact lowest 5 : {eigs_exact[:5]}")
        print(f"    CNN   lowest 5 : {eigs_cnn[:5]}")
        print("    (lowest mode expected to be the soft translational mode)")

    # ----------------------------------------------------------------
    # 5. Save
    # ----------------------------------------------------------------
    print("\n" + "=" * 60)
    print("5. SAVING")
    print("=" * 60)

    tau_grid = np.linspace(0.0, path.beta, data["N_tau"], endpoint=False)

    plot_training_history(
        train_losses, val_losses,
        save_path=str(run_dir / "training_history.png"),
    )
    plot_evaluation_results(
        eval_results,
        save_path=str(run_dir / "evaluation_results.png"),
    )
    plot_gradient_check(
        tau_grid       = tau_grid,
        val_grads_true = val_grads_norm,
        val_grads_pred = val_grads_pred,
        val_configs    = data["val_configs"],
        save_path      = str(run_dir / "gradient_check.png"),
    )
    if RUN_HESSIAN_CHECK and eigs_exact is not None:
        plot_hessian_check(
            eigs_exact, eigs_cnn,
            save_path=str(run_dir / "hessian_check.png"),
        )

    model_path = run_dir / f"dw_action_cnn_N{data['N_tau']}.pth"
    save_model(
        model, model_path,
        data         = data,
        train_losses = train_losses,
        val_losses   = val_losses,
        eval_results = eval_results,
        timestamp    = timestamp,
        physics      = {k: raw["params"].get(k) for k in ("beta", "lam", "a", "m", "bc", "mu_bias", "tau_pin")},
    )

    print(f"\n  Model saved : {model_path}")
    print(f"  Run dir     : {run_dir}")
    print("\n" + "=" * 60)
    print("DONE")
    print("=" * 60)


if __name__ == "__main__":
    main()